SCREEN_GEOMETRY = "900x600"
MASTER_PANE_WIDTH = "600"
MASTER_PANE_HEIGHT = "600"
ITEM_DESCRIPTION_WIDTH = "200"

APPLICATION_NAME = "Backpacking Weight"

CHECK_COLOR1 = 'red'
CHECK_COLOR2 = 'orange'
BACKGROUND_COLOR_MAIN = 'teal'
BUTTON_COLOR_MAIN =  '#496aa3'
TITLE_COLOR_MAIN = '#5f4194'
